export type BehaviorClass =
  | 'evaluating'
  | 'active_buyer'
  | 'category_engaged'
  | 'surface_engagement'
  | 'disqualified'

export type EnrichmentSource = 'prospeo_primary' | 'apollo_fallback' | 'hunter_domain' | 'linkedin_only'
export type ScoreTier = 'HIGH' | 'MED' | 'BELOW'
export type IcpResult = 'pass' | 'fail'

export interface SimRecord {
  id: string
  name: string
  title: string
  company: string
  geo: string
  engagementType: 'comment' | 'reaction' | 'share'
  engagementContext: string
  // ICP gate
  icpResult: IcpResult
  icpFailReason?: string
  // Classification
  behaviorClass?: BehaviorClass
  // Scoring
  score?: number
  scoreTier?: ScoreTier
  // Enrichment
  enrichmentSource?: EnrichmentSource
}

export interface SimTheme {
  id: string
  label: string
  records: SimRecord[]
}

export const SIMULATOR_THEMES: SimTheme[] = [
  {
    id: 'ai-infra',
    label: 'AI infrastructure adoption',
    records: [
      {
        id: 'r01',
        name: 'Sarah Mitchell',
        title: 'VP Engineering',
        company: 'DataLayer Inc',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Comparing managed vector DBs for production inference pipelines',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.81,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'r02',
        name: 'James Okonkwo',
        title: 'Head of AI',
        company: 'NovaTech Solutions',
        geo: 'UK',
        engagementType: 'reaction',
        engagementContext: 'Liked post on GPU cluster cost optimization',
        icpResult: 'pass',
        behaviorClass: 'surface_engagement',
        score: 0.43,
        scoreTier: 'BELOW',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'r03',
        name: 'Priya Ramanathan',
        title: 'Director of Platform',
        company: 'ScaleOps',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Mentioned switching AI infra vendors this quarter, budget approved',
        icpResult: 'pass',
        behaviorClass: 'active_buyer',
        score: 0.88,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'r04',
        name: 'Tom Berkowitz',
        title: 'Engineering Manager',
        company: 'BuildCo',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Asked which inference providers have the lowest p99 latency',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.64,
        scoreTier: 'MED',
        enrichmentSource: 'apollo_fallback',
      },
      {
        id: 'r05',
        name: 'Lisa Chen',
        title: 'CTO',
        company: 'Meridian Analytics',
        geo: 'US',
        engagementType: 'share',
        engagementContext: 'Shared analysis of AI infrastructure cost scaling patterns',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.76,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'r06',
        name: 'Raj Patel',
        title: 'Software Engineer',
        company: 'BigCorp (5,000 emp)',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Commented on model serving benchmarks',
        icpResult: 'fail',
        icpFailReason: 'Seniority: IC-level',
      },
      {
        id: 'r07',
        name: 'Emma Fischer',
        title: 'VP Product',
        company: 'Stackwise GmbH',
        geo: 'Germany',
        engagementType: 'comment',
        engagementContext: 'Discussed embedding model selection for EU customers',
        icpResult: 'fail',
        icpFailReason: 'Geo: excluded market',
      },
      {
        id: 'r08',
        name: 'Marcus Webb',
        title: 'Head of Growth',
        company: 'Axiom Data',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Evaluating AI infra vendors to reduce time-to-insight',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.69,
        scoreTier: 'MED',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'r09',
        name: 'Hina Nakamura',
        title: 'Director, Data Infra',
        company: 'Cortex Labs',
        geo: 'US',
        engagementType: 'reaction',
        engagementContext: 'Reacted to post about model observability tooling',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.55,
        scoreTier: 'MED',
        enrichmentSource: 'hunter_domain',
      },
      {
        id: 'r10',
        name: 'Dan Torres',
        title: 'Founder / CEO',
        company: 'SeedStage Co (8 emp)',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Asked about affordable GPU cloud for early-stage startups',
        icpResult: 'fail',
        icpFailReason: 'Size: 8 employees',
      },
    ],
  },
  {
    id: 'offshore-dev',
    label: 'Replacing offshore development',
    records: [
      {
        id: 's01',
        name: 'Kevin Adeyemi',
        title: 'VP Engineering',
        company: 'Vantage Software',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Comparing nearshore vs domestic teams for reliability',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.79,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 's02',
        name: 'Ananya Krishnan',
        title: 'Head of Product',
        company: 'Flink Analytics',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Described ongoing issues with offshore sprint velocity',
        icpResult: 'pass',
        behaviorClass: 'active_buyer',
        score: 0.84,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 's03',
        name: 'David Liang',
        title: 'CTO',
        company: 'Runloop Systems',
        geo: 'CA',
        engagementType: 'share',
        engagementContext: 'Shared article on hidden costs of offshore development',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.75,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 's04',
        name: 'Rachel Monroe',
        title: 'Director, Platform',
        company: 'ClipPath Inc',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Asked for vendor recommendations for replacing offshore QA team',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.71,
        scoreTier: 'MED',
        enrichmentSource: 'apollo_fallback',
      },
      {
        id: 's05',
        name: 'Omar Nassar',
        title: 'Engineering Manager',
        company: 'Depth IO',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Discussed communication overhead in distributed dev teams',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.58,
        scoreTier: 'MED',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 's06',
        name: 'Wei Zhang',
        title: 'Software Engineer',
        company: 'Momentum Corp',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Commented on async-first remote team management',
        icpResult: 'fail',
        icpFailReason: 'Seniority: IC-level',
      },
      {
        id: 's07',
        name: 'Fatima Al-Hassan',
        title: 'Head of Growth',
        company: 'Sprinto',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Mentioned exploring contractor-first model for product team',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.54,
        scoreTier: 'MED',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 's08',
        name: 'Nikhil Rao',
        title: 'VP Engineering',
        company: 'Globalink Enterprises (12k emp)',
        geo: 'IN',
        engagementType: 'comment',
        engagementContext: 'Commented on team scaling challenges',
        icpResult: 'fail',
        icpFailReason: 'Geo: excluded market',
      },
      {
        id: 's09',
        name: 'Jordan Parker',
        title: 'Engineering Manager',
        company: 'Trellis Systems',
        geo: 'US',
        engagementType: 'reaction',
        engagementContext: 'Liked post on dev team restructuring best practices',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.53,
        scoreTier: 'MED',
        enrichmentSource: 'hunter_domain',
      },
      {
        id: 's10',
        name: 'Chloe Beaumont',
        title: 'Founder / CEO',
        company: 'PrelaunchHQ (4 emp)',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Asked about cost-effective first engineering hire',
        icpResult: 'fail',
        icpFailReason: 'Size: 4 employees',
      },
    ],
  },
  {
    id: 'llm-cost',
    label: 'LLM cost benchmarking',
    records: [
      {
        id: 'l01',
        name: 'Alicia Ferreira',
        title: 'VP of AI',
        company: 'Nexus Labs',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Comparing token cost per output across frontier models',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.83,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'l02',
        name: 'Brendan Osei',
        title: 'Head of ML',
        company: 'ClearSignal AI',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Asked which providers have consistent batch inference pricing',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.77,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'l03',
        name: 'Tanaka Yoshi',
        title: 'Director of Engineering',
        company: 'Orion Systems',
        geo: 'US',
        engagementType: 'share',
        engagementContext: 'Shared LLM cost comparison spreadsheet for production apps',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.74,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'l04',
        name: 'Simone Dubois',
        title: 'CTO',
        company: 'Lumen Robotics',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Said they are migrating from GPT-4 to reduce API costs this month',
        icpResult: 'pass',
        behaviorClass: 'active_buyer',
        score: 0.91,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'l05',
        name: 'Marcus Owusu',
        title: 'Engineering Manager',
        company: 'Vertex AI Labs',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Discussed prompt caching strategies to reduce token spend',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.62,
        scoreTier: 'MED',
        enrichmentSource: 'apollo_fallback',
      },
      {
        id: 'l06',
        name: 'Ingrid Sorenson',
        title: 'Marketing Manager',
        company: 'Polaris Media',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Commented on AI writing tool pricing',
        icpResult: 'fail',
        icpFailReason: 'Title: off-target function',
      },
      {
        id: 'l07',
        name: 'Felix Hartmann',
        title: 'Head of Infrastructure',
        company: 'EuroTech GmbH',
        geo: 'Germany',
        engagementType: 'comment',
        engagementContext: 'Compared LLM providers for GDPR-compliant deployments',
        icpResult: 'fail',
        icpFailReason: 'Geo: excluded market',
      },
      {
        id: 'l08',
        name: 'Layla Mansouri',
        title: 'Engineering Manager',
        company: 'Strata Cloud',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Asked about open-source alternatives to reduce LLM spend',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.60,
        scoreTier: 'MED',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'l09',
        name: 'Aaron Tchaikovsky',
        title: 'Founder / CTO',
        company: 'NanoVault (5 emp)',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Asked about LLM pricing for bootstrapped startups',
        icpResult: 'fail',
        icpFailReason: 'Size: 5 employees',
      },
      {
        id: 'l10',
        name: 'Nadia Cohen',
        title: 'VP Engineering',
        company: 'Lighthouse AI',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Discussed cost implications of fine-tuning vs prompting',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.66,
        scoreTier: 'MED',
        enrichmentSource: 'prospeo_primary',
      },
    ],
  },
  {
    id: 'internal-ai',
    label: 'Internal AI tooling decisions',
    records: [
      {
        id: 'a01',
        name: 'Derek Okafor',
        title: 'VP Engineering',
        company: 'Paladin Software',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Comparing internal AI copilot options for developer productivity',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.80,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'a02',
        name: 'Mia Sandberg',
        title: 'Head of AI',
        company: 'Fulcrum Tech',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Said her team is choosing between Cursor and custom fine-tuned tooling this sprint',
        icpResult: 'pass',
        behaviorClass: 'active_buyer',
        score: 0.87,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'a03',
        name: 'Paulo Carvalho',
        title: 'Director of Product',
        company: 'Bridgepoint SaaS',
        geo: 'US',
        engagementType: 'share',
        engagementContext: 'Shared framework for evaluating internal AI tools for product teams',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.63,
        scoreTier: 'MED',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'a04',
        name: 'Yuki Tanabe',
        title: 'CTO',
        company: 'Cascade AI',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Evaluating build vs buy for internal LLM routing layer',
        icpResult: 'pass',
        behaviorClass: 'active_buyer',
        score: 0.89,
        scoreTier: 'HIGH',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'a05',
        name: 'Caleb Obi',
        title: 'Engineering Manager',
        company: 'Relay Systems',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Discussed AI code review tooling for mid-size eng teams',
        icpResult: 'pass',
        behaviorClass: 'evaluating',
        score: 0.67,
        scoreTier: 'MED',
        enrichmentSource: 'apollo_fallback',
      },
      {
        id: 'a06',
        name: 'Sophie Laurent',
        title: 'UX Designer',
        company: 'Collab Studio',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Commented on AI design tools in creative workflows',
        icpResult: 'fail',
        icpFailReason: 'Title: off-target function',
      },
      {
        id: 'a07',
        name: 'Ahmed Khalil',
        title: 'Head of DevOps',
        company: 'GridScale',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Discussed AI-assisted incident response tooling',
        icpResult: 'pass',
        behaviorClass: 'category_engaged',
        score: 0.58,
        scoreTier: 'MED',
        enrichmentSource: 'prospeo_primary',
      },
      {
        id: 'a08',
        name: 'Natasha Volkov',
        title: 'VP Engineering',
        company: 'Arcturus Data (11k emp)',
        geo: 'US',
        engagementType: 'comment',
        engagementContext: 'Discussed enterprise AI governance challenges',
        icpResult: 'fail',
        icpFailReason: 'Size: too large (11,000 employees)',
      },
      {
        id: 'a09',
        name: 'Leon Becker',
        title: 'Software Engineer',
        company: 'Wavefront Labs',
        geo: 'UK',
        engagementType: 'comment',
        engagementContext: 'Asked about Copilot alternatives for smaller teams',
        icpResult: 'fail',
        icpFailReason: 'Geo: excluded market',
      },
      {
        id: 'a10',
        name: 'Isabel Reyes',
        title: 'Founder / CEO',
        company: 'Nanobyte (3 emp)',
        geo: 'US',
        engagementType: 'reaction',
        engagementContext: 'Liked post on solo founder AI stack',
        icpResult: 'fail',
        icpFailReason: 'Size: 3 employees',
      },
    ],
  },
]
